### PR TITLE
Default to https protocol unless the document is using http, rather than protocol-relative

### PR DESCRIPTION
**Pull request by angusfretwell**
Hey, thanks for making this plugin! I was trying to use this with Cordova, however, as the default protocol when running on a device is file://, the script is unable to load. This pull request defaults the protocol to https://, unless the document is using http://.

### CODE REVIEW

**Comment by jacopotarantino** [comment]
Thanks for catching that! Could you remove the npm-debug.log file from the pull request? Then I'll be able to merge it in.

**Comment by angusfretwell** [comment]
Sorry, don't know how I missed that! Added it to gitignore, too ;-)

**Comment by jacopotarantino** [comment]
It's fine. I did the same thing like 2 days ago. LGTM.

**Comment by jacopotarantino** [comment]
Version 2.1.1 which contains this fix is now available.

**Comment by angusfretwell** [comment]
Awesome, thanks!

**Pull request merged**
